name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main 
env:
  CI: false
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # - run: npm ci && npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          entrypoint: './creative-html'
          target: csprep-nepal
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.SECRET_KEY }}'
          channelId: live
          projectId: csprep-org-tutor